import { DataSource } from 'typeorm';
import { ProductType } from '../../api/order/enums/product-type.enum';
import { Product } from '../../api/order/entities/product.entity';

export class ProductSeed {
  public async run(dataSource: DataSource): Promise<void> {
    const productRepository = dataSource.getRepository(Product);

    const existingCount = await productRepository.count();
    if (existingCount > 0) {
      console.log('✅ Products already seeded');
      return;
    }

    const products = [
      {
        id: 1,
        name: 'Electronics',
        description: 'Electronic devices and accessories',
        createdBy: 'admin',
        updatedBy: 'admin',
        deletedBy: 'admin',
        sku: 'ELEC-001',
        barcode: '1234567890001',
        isSales: true,
        isPurchase: true,
        isExpenses: true,
        isPointOfSale: true,
        isSubscriptions: true,
        isRental: true,
        productType: ProductType.GOODS,
        quantityOnHand: 100,
        salesPrice: 100,
        soldQuantity: 0,
      },
      {
        id: 2,
        name: 'Clothing',
        description: 'Apparel and fashion items',
        createdBy: 'admin',
        updatedBy: 'admin',
        deletedBy: 'admin',
        sku: 'CLOTH-002',
        barcode: '1234567890002',
        isSales: true,
        isPurchase: true,
        isExpenses: true,
        isPointOfSale: true,
        isSubscriptions: true,
        isRental: true,
        productType: ProductType.GOODS,
        quantityOnHand: 100,
        salesPrice: 100,
        soldQuantity: 0,
      },
      {
        id: 3,
        name: 'Books',
        description: 'Books and educational materials',
        createdBy: 'admin',
        updatedBy: 'admin',
        deletedBy: 'admin',
        sku: 'BOOK-003',
        barcode: '1234567890003',
        isSales: true,
        isPurchase: true,
        isExpenses: true,
        isPointOfSale: true,
        isSubscriptions: true,
        isRental: true,
        productType: ProductType.GOODS,
        quantityOnHand: 100,
        salesPrice: 100,
        soldQuantity: 0,
      },
      {
        id: 4,
        name: 'Home & Garden',
        description: 'Home improvement and garden supplies',
        createdBy: 'admin',
        updatedBy: 'admin',
        deletedBy: 'admin',
        sku: 'HOME-004',
        barcode: '1234567890004',
        isSales: true,
        isPurchase: true,
        isExpenses: true,
        isPointOfSale: true,
        isSubscriptions: true,
        isRental: true,
        productType: ProductType.GOODS,
        quantityOnHand: 100,
        salesPrice: 100,
        soldQuantity: 0,
      },
      {
        id: 5,
        name: 'Sports & Outdoors',
        description: 'Sports equipment and outdoor gear',
        createdBy: 'admin',
        updatedBy: 'admin',
        deletedBy: 'admin',
        sku: 'SPORT-005',
        barcode: '1234567890005',
        isSales: true,
        isPurchase: true,
        isExpenses: true,
        isPointOfSale: true,
        isSubscriptions: true,
        isRental: true,
        productType: ProductType.GOODS,
        quantityOnHand: 100,
        salesPrice: 100,
        soldQuantity: 0,
      },
      {
        id: 6,
        name: 'Health & Beauty',
        description: 'Health and beauty products',
        createdBy: 'admin',
        updatedBy: 'admin',
        deletedBy: 'admin',
        sku: 'HEALTH-006',
        barcode: '1234567890006',
        isSales: true,
        isPurchase: true,
        isExpenses: true,
        isPointOfSale: true,
        isSubscriptions: true,
        isRental: true,
        productType: ProductType.GOODS,
        quantityOnHand: 100,
        salesPrice: 100,
        soldQuantity: 0,
      },
      {
        id: 7,
        name: 'Toys & Games',
        description: 'Toys, games, and entertainment',
        createdBy: 'admin',
        updatedBy: 'admin',
        deletedBy: 'admin',
        sku: 'TOYS-007',
        barcode: '1234567890007',
        isSales: true,
        isPurchase: true,
        isExpenses: true,
        isPointOfSale: true,
        isSubscriptions: true,
        isRental: true,
        productType: ProductType.GOODS,
        quantityOnHand: 100,
        salesPrice: 100,
        soldQuantity: 0,
      },
      {
        id: 8,
        name: 'Automotive',
        description: 'Car parts and automotive accessories',
        createdBy: 'admin',
        updatedBy: 'admin',
        deletedBy: 'admin',
        sku: 'AUTO-008',
        barcode: '1234567890008',
        isSales: true,
        isPurchase: true,
        isExpenses: true,
        isPointOfSale: true,
        isSubscriptions: true,
        isRental: true,
        productType: ProductType.GOODS,
        quantityOnHand: 100,
        salesPrice: 100,
        soldQuantity: 0,
      },
    ];

    for (const productData of products) {
      const product = productRepository.create(productData);
      await productRepository.save(product);
    }

    console.log(`✅ Seeded ${products.length} products`);
  }
}
